services:
  web:
    build: .
    ports:
      - "${WEB_PORT:-5001}:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - PORT=5000
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password12345678}
    depends_on:
      - neo4j
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  neo4j:
    build:
      context: .
      dockerfile: Dockerfile.neo4j
    ports:
      - "${NEO4J_BROWSER_PORT:-7474}:7474"   # Neo4j Browser
      - "${NEO4J_BOLT_PORT:-7687}:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-password12345678}
      - NEO4J_apoc_export_file_enabled=${NEO4J_APOC_EXPORT_ENABLED:-true}
      - NEO4J_apoc_import_file_enabled=${NEO4J_APOC_IMPORT_ENABLED:-true}
      - NEO4J_apoc_import_file_use__neo4j__config=${NEO4J_APOC_USE_CONFIG:-true}
      - NEO4J_dbms_security_procedures_unrestricted=${NEO4J_SECURITY_PROCEDURES:-apoc.*}
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
